before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: K7fwPo9ZbHl7ltG/2m6aP1m0BnVmTltNP/Wqwn31ssVkHT7+OPbys6EZxFrgrMXjHhkOgZ1bb68qEddEVeauSoT4ms0D49Cvq+gVAa5L4exZ6IF7yhzRzSWcuvmQv1H97OCE3nsg4IUfCt1wjAeop6l3Eu/rGvURVTEmDUjq0Bdty6oLCFN/CkyMB68yZ6LgFBxjZ9dnUzKQ2KJyffqoPCUHy/x4lbAZLG8ukMP9j8FRlAmXVdxC2uGrGqv4UWu+xx5wk3ZVIymtCYUKTt2P+6p7g9j+jsHFHr+5aGCawdzB53j7+kTikxn8ylkKBNPqYlOpNp4S02AAjtvdfWJ+FeYZfHvZ26RUoaNxsnuXXRVvC6D82slnHzZEOUWn6Spqo+fNLodYHhMdEewbyuS+wqt0IQG1a1pX3HakDzpqtTWrxSK7whS/+glibRDJuBmDW8SIVzd2/2aNYtMdcEL3AlqVvVJr6jrB4qk6Vo2pJNl3R1T/gMkojuoHcNhlhe7Bhw2UwFzXs2J56MGCTy3mHpZdKPpWI8De+qGmZ+q8ZUsuOT+m/eGbOVOaGx9fGnUtFnKG73PQ+ytI/e4iovIAsiX1sSVyJ1YWKu2m3wUdrnfoSpJe+OhvXcUEZFIZMlxXX/q8u9IyGHFyMp6k4ya5jSVpm+zSaeYWf+gf7kWWKkg= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
